{% set name = "expandvars" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expandvars-{{ version }}.tar.gz
  sha256: 7d1adfa55728cf4b5d812ece3d087703faea953e0c0a1a78415de9df5024d844

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - expandvars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sayanarijit/expandvars
  summary: Expand system variables Unix style
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tierriminator
