{% set name = "expandvars" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/expandvars-{{ version }}.tar.gz
  sha256: f04070b8260264185f81142cd85e5df9ceef7229e836c5844302c4ccfa00c30d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - expandvars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sayanarijit/expandvars
  summary: Expand system variables Unix style
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tierriminator
