{% set name = "expandvars" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/expandvars-{{ version }}.tar.gz
  sha256: 98add8268b760dfee457bde1c17bf745795fdebc22b7ddab75fd3278653f1e05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - expandvars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sayanarijit/expandvars
  summary: Expand system variables Unix style
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tierriminator
